# ==============================================================================
# Wanas Heat Recovery Unit (Rekuperator) - ESPHome Modbus Integration
# 
# Hardware: ESP32 + RS485 module (e.g., KAmodESP32 POW+RS485)
# Firmware: ESPHome
# Tested on: Wanas 815 V Hi-Tech (Controller by Tech Controllers)
# ==============================================================================

esphome:
  name: wanas-hvac
  friendly_name: Wanas HVAC

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  baud_rate: 115200

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local

  ap:
    ssid: "Wanas Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# ==============================================================================
# HARDWARE CONFIGURATION: UART & RS485
# ==============================================================================
uart:
  id: mod_bus
  tx_pin: GPIO25
  # CRUCIAL HARDWARE FIX 1: Internal Pullup on RX
  # Prevents electromagnetic noise from triggering false CRC errors when 
  # the flow control pin rapidly switches from TX to RX.
  rx_pin:
    number: GPIO27
    mode:
      input: true
      pullup: true
  baud_rate: 9600
  rx_buffer_size: 256
  # CRUCIAL HARDWARE FIX 2: Spoofing 2 Stop Bits
  # ESP32 has a known hardware timing quirk where `flush()` reports complete 
  # before the last bit physically leaves the shift register. ESPHome then 
  # switches the flow control pin too early, cutting off the Modbus query. 
  # By sending 2 stop bits, the cutoff severs the extra (useless) bit, 
  # delivering a perfectly intact packet to the Wanas controller.
  stop_bits: 2

modbus:
  id: modbus1
  uart_id: mod_bus
  flow_control_pin: GPIO26
  # Wanas controller is very slow to respond. Give it time to process.
  send_wait_time: 500ms

modbus_controller:
  - id: wanas
    address: 1
    modbus_id: modbus1
    setup_priority: -10
    # Read all sensors every 15 seconds. Do not query faster, 
    # as the Tech Controllers board easily gets overwhelmed.
    update_interval: 15s
    # Wait 250ms between each consecutive register query to give the 
    # Wanas controller time to breathe.
    command_throttle: 250ms

# ==============================================================================
# SENSORS (READ-ONLY)
# ==============================================================================
sensor:
  # --- Temperatures (with 1-decimal precision) ---
  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Outside Temperature"
    register_type: holding
    address: 4
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      # Clamp ensures values stay within reasonable limits (-50 to 100)
      - clamp:
          min_value: -50.0
          max_value: 100.0
          ignore_out_of_range: true # This makes it drop the 6553.5 instead of rounding it

  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Exhaust Temperature"
    register_type: holding
    address: 5
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - clamp:
          min_value: -50.0
          max_value: 100.0
          ignore_out_of_range: true

  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Humidifier Internal Temperature"
    register_type: holding
    address: 6
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - clamp:
          min_value: -50.0
          max_value: 100.0
          ignore_out_of_range: true

  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Room Temperature"
    register_type: holding
    address: 7
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - clamp:
          min_value: -50.0
          max_value: 100.0
          ignore_out_of_range: true

  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Supply Temperature"
    register_type: holding
    address: 29
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - clamp:
          min_value: -50.0
          max_value: 100.0
          ignore_out_of_range: true

  # --- Humidity (with 1-decimal precision) ---
  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Room Humidity"
    register_type: holding
    address: 55
    value_type: U_WORD
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - clamp:
          min_value: 0.0
          max_value: 100.0
          ignore_out_of_range: true

  # --- Airflows (Integer) ---
  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Supply Airflow"
    register_type: holding
    address: 0
    value_type: U_WORD
    unit_of_measurement: "m³/h"
    icon: "mdi:fan-plus"
    state_class: measurement
    filters:
      - clamp:
          min_value: 0.0
          max_value: 2000.0
          ignore_out_of_range: true

  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Extract Airflow"
    register_type: holding
    address: 1
    value_type: U_WORD
    unit_of_measurement: "m³/h"
    icon: "mdi:fan-minus"
    state_class: measurement
    filters:
      - clamp:
          min_value: 0.0
          max_value: 2000.0
          ignore_out_of_range: true

# ==============================================================================
# STATUS FLAGS (READ-ONLY)
# ==============================================================================
binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Bypass Open"
    register_type: holding
    address: 31
    bitmask: 1
    device_class: opening

  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Humidifier Active"
    register_type: holding
    address: 32
    bitmask: 1
    device_class: moisture

  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Heater Active"
    register_type: holding
    address: 33
    bitmask: 1
    device_class: heat

# ==============================================================================
# CONTROLS (READ / WRITE)
# ==============================================================================
switch:
  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Humidifier Toggle"
    register_type: holding
    address: 40
    bitmask: 1
    icon: "mdi:water"

number:
  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Party Mode Timer"
    register_type: holding
    address: 45
    value_type: U_WORD
    min_value: 0
    max_value: 720
    step: 15
    unit_of_measurement: "min"
    icon: "mdi:party-popper"

select:
  # Note: Wanas physical wall panel MUST be set to "Manual" mode for 
  # this gear selector to work. In "Program" mode, Modbus gear changes are ignored.
  - platform: modbus_controller
    modbus_controller_id: wanas
    name: "Target Gear"
    address: 2
    value_type: U_WORD
    optionsmap:
      "Gear 1": 1
      "Gear 2": 2
      "Gear 3": 3
    icon: "mdi:fan"
